# Day 2 Exercises (NumPy + Matplotlib)

## Part 1: Basic NumPy Operations
a) Generate an array of numbers 0-24. Reshape to a 5x5 matrix.

In [10]:
import numpy as np  # We'll do this once for the whole littany of exercises

mat = np.arange(25).reshape(5,5)
print(mat)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


b) Extract the diagonal of this matrix.

In [11]:
diag = np.diag(mat)
print(diag)

[ 0  6 12 18 24]


c) Multiply the matrix by an identity matrix of the same shape. Confirm that it is identical to the original.

Hint: Use `np.all` command to confirm all equal. 

In [12]:
## Construct identity matrix.
idmat = np.identity(5)
## Note that we could also have passed mat.shape[0] instead of 5. Then our code would be agnostic about the shape of
## mat (other than its being square) and would work as-is even if we had done a 6x6 or 8x8 example or whatever.

## Matrix multiplication.
mat2 = mat @ idmat

## Confirm all equal.
print( np.all(mat == mat2) )

## As a one-liner, if we didn't need to hold onto any of the intermediate values, we could also have done:
## np.all( mat == (mat @ np.identity(mat.shape[0])) )

True


d) Join the matrix with itself and return a new matrix with shape (2,5,5).

In [23]:
## Here's one simple way to do this
mat3 = np.array([mat, mat])
print(mat3.shape)
print(mat3)

## Note that np.vstack will NOT work (that glues along axis zero, to make a 10x5 array)

## However, np.concatenate along with prepending a length-1 axis to mat *will* work
## (but it's more complex and less readable)
## print(np.concatenate( (mat[np.newaxis,...],mat[np.newaxis,...]) ))

(2, 5, 5)
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]
  [20 21 22 23 24]]

 [[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]
  [20 21 22 23 24]]]


e) Compute the mean of the concatenated matrix along the first axis. Confirm its equal to the original matrix.

In [24]:
## Take mean.
avg_of_both_mats_in_mat3 = mat3.mean(axis=0)

## Taking the mean along axis0 means you traverse along that axis.  So you'd be taking 25 means, i.e. the mean of
## 0 & 0, and the mean of 1 & 1, 2 & 2, etc to fill the 5x5 slots.  But that would just give us a copy of mat, right?
print(avg_of_both_mats_in_mat3)

## Confirm all equal.
print( np.all(mat == avg_of_both_mats_in_mat3) )

[[ 0.  1.  2.  3.  4.]
 [ 5.  6.  7.  8.  9.]
 [10. 11. 12. 13. 14.]
 [15. 16. 17. 18. 19.]
 [20. 21. 22. 23. 24.]]
True


f) Return the indices of the matrix where the elements are greater than 15.

In [29]:
# This is precisely what np.where() does if you don't give the optional [x y] arguments listed in the docstring
print(np.where(mat > 15))
# That's all the axis0 indices and the corresponding axis1 indices of the pertinent elements.

# If you want these indices formatted as (axis0,axis1) pairs, we can use Python's zip function
# along with Python's * operator (to unpack the pair of arrays, since zip wants each array as a separate argument)
list(zip(*np.where(mat > 15)))

(array([3, 3, 3, 3, 4, 4, 4, 4, 4]), array([1, 2, 3, 4, 0, 1, 2, 3, 4]))


[(3, 1), (3, 2), (3, 3), (3, 4), (4, 0), (4, 1), (4, 2), (4, 3), (4, 4)]

g) Using `np.where`, set all elements of the matrix greater than 15 to 1, else 0.


In [33]:
# For this, use the other syntax of np.where(), which *will* return a (brand new) array meeting the specified conditions
print(np.where(mat > 15, 1, 0))
# Note that "set" here is a bit of a misnomer, since fancy indexing using np.where() will trigger a copy

# Fun alternate solution w/o where():
# Make the boolean matrix (mat > 15) -- remember, comparisons are vectorized! -- and reinterpret
# False as 0 and True as 1 by viewing to int8 (bools occupy one byte, so to change the view rather than make a copy,
# we should review as a byte-sized int)
print((mat > 15).view(dtype=np.int8))

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 1 1 1 1]
 [1 1 1 1 1]]
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 1 1 1 1]
 [1 1 1 1 1]]


h) Set all elements of the matrix greater than 15 to 2, less than 5 to 1, else 0.

Hint: `np.where` can be passed as an input to `np.where`.

In [34]:
np.where(mat > 15, 2, np.where(mat > 5, 1, 0))

array([[0, 0, 0, 0, 0],
       [0, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 2, 2, 2, 2],
       [2, 2, 2, 2, 2]])

i) Return the lower triangle of the original matrix.

In [35]:
# This requires reading about the "linear-algebra-friendly-functions" part of the notebook
print(np.tril(mat))

[[ 0  0  0  0  0]
 [ 5  6  0  0  0]
 [10 11 12  0  0]
 [15 16 17 18  0]
 [20 21 22 23 24]]


j) Define a demean function.

In [37]:
def demean(arr):
    """De-mean array."""
    return arr - np.mean(arr)

k) Apply the demean function across each row of the matrix.

In [45]:
# You can use np.apply_along_axis to move along axis1
print(np.apply_along_axis(demean, 1, mat))

# But note that the "return" line of demean() would come close to accomplishing this if we put 'mat' in place of 'arr',
# thanks to broadcasting rules.  So using the demean() function at all is unnecessary if take means along axis1 and
# have it keep the axis0 dimension...
print(mat)
print(np.mean(mat, axis=1, keepdims=True))
print(mat - np.mean(mat, axis=1, keepdims=True))

[[-2. -1.  0.  1.  2.]
 [-2. -1.  0.  1.  2.]
 [-2. -1.  0.  1.  2.]
 [-2. -1.  0.  1.  2.]
 [-2. -1.  0.  1.  2.]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[ 2.]
 [ 7.]
 [12.]
 [17.]
 [22.]]
[[-2. -1.  0.  1.  2.]
 [-2. -1.  0.  1.  2.]
 [-2. -1.  0.  1.  2.]
 [-2. -1.  0.  1.  2.]
 [-2. -1.  0.  1.  2.]]


## Bonus: Spike Detection

In the following exercises, you will be manipulating, analyzing, and visualizing preprocessed extracellular electrophysiological data. Specifically, the following 10s recording was taken from the abdomen of a crayfish. Action potentials are readily apparent throughout the entire recording. 

First, we load the data.

In [ ]:
import numpy as np

## Load data.
npz = np.load('spikes.npz')
data = npz['data'] * 1e6      # Convert to uV
times = npz['times']

a) Plot the entire raw recording. Do multiple types of spikes appear to be present?

b) In a recent paper, [Rey et al. (2015)](https://www.sciencedirect.com/science/article/pii/S0361923015000684) suggest a simple spike detection technique via data-driven amplitude thresholding. Specifically, they propose an automated amplitude threshold that defined as multiple of an estimate of the standard deviation of the noise:

$$ \text{threshold} = k \cdot \hat{\sigma}_n $$

where $k$ is a constant typically between 3-5; and $\hat{\sigma}_n$ is an estimate of the standard deviation of the noise, defined as:

$$ \hat{\sigma}_n = \frac{\text{median} \left( |X| \right)}{0.6745} $$ 

where $|X|$ is the absolute value of the raw data.

Write a function that returns the amplitude threshold as defined above. The function should accept as arguments the raw data, $X$, and the constant, $k$. 

c) Next we need a function that can detect slices of the raw signal that exceed the threshold. This ultimately becomes a clustering problem (i.e. identifying "islands" of signal rising above an "ocean of noise"). Though this is definitely doable with core NumPy, the SciPy library has built-in functions specifically written for these purposes. 

Because these functions are beyond the scope of the bootcamp, we have provided a peak finding function for you. The function, `peak_finder`, accepts a raw data trace and a threshold. It then finds all clusters of samples above a threshold, and returns the index and signal magnitude corresponding to the peak of each cluster.

The function relies on the `measurements` tools from scipy.ndimage. For a tutorial, see [here](https://dragly.org/2013/03/25/working-with-percolation-clusters-in-python/).



In [ ]:
def peak_finder(X, thresh):
    """Simple peak finding algorithm.
    
    Parameters
    ----------
    X : array_like, shape (n_times,)
        Raw data trace.
    thresh : float
        Amplitude threshold.
        
    Returns
    -------
    peak_loc : array_like, shape (n_clusters,)
        Index of peak amplitudes.
    peak_mag : array_like, shape (n_clusters,)
        Magnitude of peak amplitudes.
    """
    import numpy as np
    from scipy.ndimage import measurements
    
    ## Error-catching.
    assert X.ndim == 1
    
    ## Identify clusters.
    clusters, ix = measurements.label(X > thresh)
    
    ## Identify index of peak amplitudes. 
    peak_loc = np.concatenate(measurements.maximum_position(X, labels=clusters, index=np.arange(ix)+1))
    
    ## Identify magnitude of peak amplitudes.
    peak_mag = measurements.maximum(X, labels=clusters, index=np.arange(ix)+1)
    return peak_loc, peak_mag

d) Apply the peak detection algorithm to the raw data using a constant $k=6$. Plot a histogram of the spike amplitudes (try bins of 0-150 in increments of 5 uV). 

How many spikes are detected? How many types of spikes do there appear to be?

e) Plot the first second of the data. Using a scatterplot (or any other method you can think of), indicate the peak for each detected spike.

f) Remake the plot above, but repeating the procedure with a constant $k=2$. How trustworthy is the spike detection algorithm with this more liberal threshold?

g) Returning now to the detected spikes when $k=6$, define a set of boundaries that divides the spikes into three clusters. How many spikes are in each cluster?

h) Action potentials last roughly 1-2 milliseconds. With this in mind, extract a 3 ms window around each detected spike; that is, extract 1.5 ms of samples on either side of the detected peak. Store each epoch according to its cluster. 

Hint: The data were recorded at 10 KHz meaning there are 10 samples per millisecond. 

i) Plot each averaged spike waveform in a single plot. Add a legend denoting the spike cluster.

## RGB images (from MIT Lincoln Labs)

A digital image is simply an array of numbers, which instructs a grid of pixels on a monitor to shine light of specific colors, according to the numerical values in that array.

An RGB-image can thus be stored as a 3D NumPy array of shape-(V,H,3). V is the number of pixels along the vertical direction, H is the number of pixels along the horizontal, and the size-3 dimension stores the red, blue, and green color values for a given pixel. Thus a (32,32,3)

array would be a 32x32 RGB image.

You often work with a collection of images. Suppose we want to store N images in a single array; thus we now consider a 4D shape-(N, V, H, 3) array. For the sake of convenience, let’s simply generate a 4D-array of random numbers as a placeholder for real image data.

Specifically:

* generate a 4D array that holds 500, 48x48 random RGB images (think about the shape this array should have, and use np.random.rand liberally)

* then, normalize those images (by dividing through by max intensity) so that the largest intensity within each color channel within each image is set to 1, but relative intensities are preserved.

#### Comment on the array shape

Focus for a moment on a single RGB image (which will be a 3D array). There's a question (with no cut-and-dry correct answer) about which of two shapes feels more natural for this structure.  Let's compare two candidates (48,48,3) vs (3,48,48)  (I think we can all agree that (48,3,48) is unnatural and weird for a host of reasons, but chime in if you think we're mistaken about that).

**(48,48,3)** -- this shape lends itself to thinking about a single 48x48 object (the image as you'd probably view it, namely as a 48x48 square of pixels), with a trio of numbers (the R, G, and B intensities) stored on each pixel.  This is also the shape that the exercise suggested.  But you'd be perfectly within your rights to instead opt for...

**(3,48,48)** -- this shape instead lends itself to conceiving of this as 3 "channels" at top level (i.e. axis0 level) -- a Red channel, a Green, and a Blue -- and that associated with each channel is a 48x48 image.  This view might feel more natural if you want to think in terms of "color filters", and thinking of each image as really being 3 separate images (one Red, one Green, one Blue) that you'd overlay to make the composite image.

So which view is "correct"?  Or "better"?  Again, no right answer to this.  It really depends on how you want to conceptualize the composite image and on which shape will make slicing easier on your cognitively given the tasks you want to perform with these images.  The answers show things both ways.

Either way, it's probably most natural to have the N=500 axis *pre*pended to that shape -- so (500,48,48,3) or (500,3,48,48).  That makes it natural to conceptualize this (again, if we tend to think in axis0-first order) as 500 versions of whichever of the two shapes above you opted for.

### (48,48,3)-based solution

In [2]:
import numpy as np
# Generate a collection of 500 48x48 RGB images
images = np.random.rand(500, 48, 48, 3)

In [3]:
# Find the max-intensity within each color-channel of each image...

# The `axis` option tells max() to treat all the data along axes 1 & 2 (for fixed indices on axes 0 & 3)
# as though those 48x48 values were all a single 1D chain, and to take the max among them. The net effect
# is to replace axes 1 & 2 (again, for each fixed pair of indices on axes 0 & 3) with a scalar, namely the
# max value.  The result will be a 500x3 array holding the maxR, maxG, and maxB values for each of the 500 images.
max_RGB = images.max(axis=(1,2))  
max_RGB.shape  # No need for print() -- notebook will display the last variable referenced by default

(500, 3)

In [4]:
# Now we want to broadcast-divide all the R,G,B values on each by their respective maxes in one vectorized swoop.
# But (500,3) isn't compatible with (500,48,48,3) (make sure you understand *why* based on broadcasting rules).
# But we can make them compatible by manually inserting size-1 dimensions so that the maxes take on shape
# (500, 1, 1, 3).  And that allows us to divide in a vectorize numpythonic way.  Note: no need to have a new variable
# point to the reshaped array, since once the division is over, we don't need to hold on to the reshaped version.
normed_images = images / max_RGB.reshape(500, 1, 1, 3)

# Note: slicing max_RGB with some np.newaxis-es thrown in would also have worked (remembering, slicing and/or
# using newaxis and/or using reshape change only the *view*, not the *data*. Like this...
# normed_images = images / max_RGB[:, np.newaxis, np.newaxis, :]

In [5]:
# That's it.  Four-line solution(after importing numpy). Did it work?  Here's a sanity check...

# Are all the max-values now 1?
print(normed_images.max(axis=(1,2)))

# And more rigorously
np.all(normed_images.max(axis=(1,2)) == 1.0)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 ...
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


True

### (3,48,48)-based solution

In [6]:
import numpy as np
# Generate a collection of 500 48x48 RGB images
images = np.random.rand(500, 3, 48, 48)

In [7]:
# Find the max-intensity within each color-channel of each image...

# The `axis` option tells max() to treat all the data along axes 2 & 3 (for fixed indices on axes 0 & 1)
# as though those 48x48 values were all a single 1D chain, and to take the max among them. The net effect
# is to replace axes 2 & 3 (again, for each fixed pair of indices on axes 0 & 1) with a scalar, namely the
# max value.  The result will be a 500x3 array holding the maxR, maxG, and maxB values for each of the 500 images.
max_RGB = images.max(axis=(2,3))  
max_RGB.shape  # No need for print() -- notebook will display the last variable referenced by default

(500, 3)

In [8]:
# Now we want to broadcast-divide all the R,G,B values on each by their respective maxes in one vectorized swoop.
# But (500,3) isn't compatible with (500,3, 48,48) (make sure you understand *why* based on broadcasting rules).
# But we can make them compatible by manually inserting size-1 dimensions so that the maxes take on shape
# (500, 3, 1, 1).  And that allows us to divide in a vectorize numpythonic way.  Note: no need to have a new variable
# point to the reshaped array, since once the division is over, we don't need to hold on to the reshaped version.
normed_images = images / max_RGB.reshape(500, 3, 1, 1)

# Note: slicing max_RGB with some np.newaxis-es thrown in would also have worked (remembering, slicing and/or
# using newaxis and/or using reshape change only the *view*, not the *data*. Like this...
# normed_images = images / max_RGB[:, :, np.newaxis, np.newaxis]
# Or, since the 500 & 3 dims are grouped, we could have used an Ellipsis:
# normed_images = images / max_RGB[..., np.newaxis, np.newaxis]

In [9]:
# That's it.  Four-line solution (after importing numpy). Did it work?  Here's a sanity check...

# Are all the max-values now 1?
print(normed_images.max(axis=(2,3)))

# And more rigorously
np.all(normed_images.max(axis=(2,3)) == 1.0)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 ...
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


True

## EEG time series (adapted from Richard Gao at UCSD)

The file EEG_exp.mat contains binary MATLAB data that scipy.io.loadmat() (see below) will pull into a dictionary.  Pertinent keys in that dict:

* 'EEG' -- a 1D array of over 700K floats, representing EEG data (in microV) sampled at a rate given by...
* 'fs' -- the sampling frequency, in Hz
* 'trial_info' -- a 2D array (300x2), each row of which contains the time (in seconds) after start of the  experiment at which some stimulus was applied to the subject followed an integer 1,2, or 3 denoting  the kind of stimulus

Assume the trial_info timestamps and EEG data are both sampled ar rate fs so that no "fudging" is necessary with timestamps.

Your goal is to do the following:

1) For each event in trial_info, find the index of the corresponding time in the EEG data

2) Pull out a subarray of EEG data in a window (epoch) around that time, that stretches from 0.5 seconds before the event to 1 second after the event

3) Make an array of times (can be the same for all events) that labels the event time within this window as t=0, with negative/positive t values for parts of the epoch before/after the event.

4) Subtract off a baseline from all the values in each epoch (baseline should be the mean of just the t<0 times in that epoch)

5) Now aggregate all the events of category 1 and generate a single "averaged" de-baselined signal over all category 1 events.  Do likewise for the category 2 & 3 events.

6) Make a single plot (with labelled axes and, ideally, a legend) showing the average signal for each of the three categories of stimulus.

The key is to try to leverage what you've learned about numpy and matplotlib to do these operations efficiently and end up with fairly streamlined (but still readable) code.

Good luck!


In [ ]:
import numpy as np
import matplotlib.pyplot as plt
from scipy import io # this submodule let's us load the signal we want
%matplotlib inline

In [ ]:
# You'll need a scipy utility function to read this MATLAB data file
# scipy loads .mat file into a dictionary
# the details are not crucial, we just have to unpack them into python variables.

# So something like...
EEG_data = io.loadmat('EEG_exp.mat', squeeze_me = True)