# Day 2 Exercises (NumPy + Matplotlib)

## Part 1: Basic NumPy Operations
a) Generate an array of numbers 0-24. Reshape to a 5x5 matrix.

In [10]:
import numpy as np  # We'll do this once for the whole littany of exercises

mat = np.arange(25).reshape(5,5)
print(mat)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


b) Extract the diagonal of this matrix.

In [11]:
diag = np.diag(mat)
print(diag)

[ 0  6 12 18 24]


c) Multiply the matrix by an identity matrix of the same shape. Confirm that it is identical to the original.

Hint: Use `np.all` command to confirm all equal. 

In [12]:
## Construct identity matrix.
idmat = np.identity(5)
## Note that we could also have passed mat.shape[0] instead of 5. Then our code would be agnostic about the shape of
## mat (other than its being square) and would work as-is even if we had done a 6x6 or 8x8 example or whatever.

## Matrix multiplication.
mat2 = mat @ idmat

## Confirm all equal.
print( np.all(mat == mat2) )

## As a one-liner, if we didn't need to hold onto any of the intermediate values, we could also have done:
## np.all( mat == (mat @ np.identity(mat.shape[0])) )

True


d) Join the matrix with itself and return a new matrix with shape (2,5,5).

In [23]:
## Here's one simple way to do this
mat3 = np.array([mat, mat])
print(mat3.shape)
print(mat3)

## Note that np.vstack will NOT work (that glues along axis zero, to make a 10x5 array)

## However, np.concatenate along with prepending a length-1 axis to mat *will* work
## (but it's more complex and less readable)
## print(np.concatenate( (mat[np.newaxis,...],mat[np.newaxis,...]) ))

(2, 5, 5)
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]
  [20 21 22 23 24]]

 [[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]
  [20 21 22 23 24]]]


e) Compute the mean of the concatenated matrix along the first axis. Confirm its equal to the original matrix.

In [24]:
## Take mean.
avg_of_both_mats_in_mat3 = mat3.mean(axis=0)

## Taking the mean along axis0 means you traverse along that axis.  So you'd be taking 25 means, i.e. the mean of
## 0 & 0, and the mean of 1 & 1, 2 & 2, etc to fill the 5x5 slots.  But that would just give us a copy of mat, right?
print(avg_of_both_mats_in_mat3)

## Confirm all equal.
print( np.all(mat == avg_of_both_mats_in_mat3) )

[[ 0.  1.  2.  3.  4.]
 [ 5.  6.  7.  8.  9.]
 [10. 11. 12. 13. 14.]
 [15. 16. 17. 18. 19.]
 [20. 21. 22. 23. 24.]]
True


f) Return the indices of the matrix where the elements are greater than 15.

In [29]:
# This is precisely what np.where() does if you don't give the optional [x y] arguments listed in the docstring
print(np.where(mat > 15))
# That's all the axis0 indices and the corresponding axis1 indices of the pertinent elements.

# If you want these indices formatted as (axis0,axis1) pairs, we can use Python's zip function
# along with Python's * operator (to unpack the pair of arrays, since zip wants each array as a separate argument)
list(zip(*np.where(mat > 15)))

(array([3, 3, 3, 3, 4, 4, 4, 4, 4]), array([1, 2, 3, 4, 0, 1, 2, 3, 4]))


[(3, 1), (3, 2), (3, 3), (3, 4), (4, 0), (4, 1), (4, 2), (4, 3), (4, 4)]

g) Using `np.where`, set all elements of the matrix greater than 15 to 1, else 0.


In [33]:
# For this, use the other syntax of np.where(), which *will* return a (brand new) array meeting the specified conditions
print(np.where(mat > 15, 1, 0))
# Note that "set" here is a bit of a misnomer, since fancy indexing using np.where() will trigger a copy

# Fun alternate solution w/o where():
# Make the boolean matrix (mat > 15) -- remember, comparisons are vectorized! -- and reinterpret
# False as 0 and True as 1 by viewing to int8 (bools occupy one byte, so to change the view rather than make a copy,
# we should review as a byte-sized int)
print((mat > 15).view(dtype=np.int8))

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 1 1 1 1]
 [1 1 1 1 1]]
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 1 1 1 1]
 [1 1 1 1 1]]


h) Set all elements of the matrix greater than 15 to 2, less than 5 to 1, else 0.

Hint: `np.where` can be passed as an input to `np.where`.

In [34]:
np.where(mat > 15, 2, np.where(mat > 5, 1, 0))

array([[0, 0, 0, 0, 0],
       [0, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 2, 2, 2, 2],
       [2, 2, 2, 2, 2]])

i) Return the lower triangle of the original matrix.

In [35]:
# This requires reading about the "linear-algebra-friendly-functions" part of the notebook
print(np.tril(mat))

[[ 0  0  0  0  0]
 [ 5  6  0  0  0]
 [10 11 12  0  0]
 [15 16 17 18  0]
 [20 21 22 23 24]]


j) Define a demean function.

In [37]:
def demean(arr):
    """De-mean array."""
    return arr - np.mean(arr)

k) Apply the demean function across each row of the matrix.

In [45]:
# You can use np.apply_along_axis to move along axis1
print(np.apply_along_axis(demean, 1, mat))

# But note that the "return" line of demean() would come close to accomplishing this if we put 'mat' in place of 'arr',
# thanks to broadcasting rules.  So using the demean() function at all is unnecessary if take means along axis1 and
# have it keep the axis0 dimension...
print(mat)
print(np.mean(mat, axis=1, keepdims=True))
print(mat - np.mean(mat, axis=1, keepdims=True))

[[-2. -1.  0.  1.  2.]
 [-2. -1.  0.  1.  2.]
 [-2. -1.  0.  1.  2.]
 [-2. -1.  0.  1.  2.]
 [-2. -1.  0.  1.  2.]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[ 2.]
 [ 7.]
 [12.]
 [17.]
 [22.]]
[[-2. -1.  0.  1.  2.]
 [-2. -1.  0.  1.  2.]
 [-2. -1.  0.  1.  2.]
 [-2. -1.  0.  1.  2.]
 [-2. -1.  0.  1.  2.]]


## RGB images (from MIT Lincoln Labs)

A digital image is simply an array of numbers, which instructs a grid of pixels on a monitor to shine light of specific colors, according to the numerical values in that array.

An RGB-image can thus be stored as a 3D NumPy array of shape-(V,H,3). V is the number of pixels along the vertical direction, H is the number of pixels along the horizontal, and the size-3 dimension stores the red, blue, and green color values for a given pixel. Thus a (32,32,3)

array would be a 32x32 RGB image.

You often work with a collection of images. Suppose we want to store N images in a single array; thus we now consider a 4D shape-(N, V, H, 3) array. For the sake of convenience, let’s simply generate a 4D-array of random numbers as a placeholder for real image data.

Specifically:

* generate a 4D array that holds 500, 48x48 random RGB images (think about the shape this array should have, and use np.random.rand liberally)

* then, normalize those images (by dividing through by max intensity) so that the largest intensity within each color channel within each image is set to 1, but relative intensities are preserved.

#### Comment on the array shape

Focus for a moment on a single RGB image (which will be a 3D array). There's a question (with no cut-and-dry correct answer) about which of two shapes feels more natural for this structure.  Let's compare two candidates (48,48,3) vs (3,48,48)  (I think we can all agree that (48,3,48) is unnatural and weird for a host of reasons, but chime in if you think we're mistaken about that).

**(48,48,3)** -- this shape lends itself to thinking about a single 48x48 object (the image as you'd probably view it, namely as a 48x48 square of pixels), with a trio of numbers (the R, G, and B intensities) stored on each pixel.  This is also the shape that the exercise suggested.  But you'd be perfectly within your rights to instead opt for...

**(3,48,48)** -- this shape instead lends itself to conceiving of this as 3 "channels" at top level (i.e. axis0 level) -- a Red channel, a Green, and a Blue -- and that associated with each channel is a 48x48 image.  This view might feel more natural if you want to think in terms of "color filters", and thinking of each image as really being 3 separate images (one Red, one Green, one Blue) that you'd overlay to make the composite image.

So which view is "correct"?  Or "better"?  Again, no right answer to this.  It really depends on how you want to conceptualize the composite image and on which shape will make slicing easier on your cognitively given the tasks you want to perform with these images.  The answers show things both ways.

Either way, it's probably most natural to have the N=500 axis *pre*pended to that shape -- so (500,48,48,3) or (500,3,48,48).  That makes it natural to conceptualize this (again, if we tend to think in axis0-first order) as 500 versions of whichever of the two shapes above you opted for.

### (48,48,3)-based solution

In [2]:
import numpy as np
# Generate a collection of 500 48x48 RGB images
images = np.random.rand(500, 48, 48, 3)

In [3]:
# Find the max-intensity within each color-channel of each image...

# The `axis` option tells max() to treat all the data along axes 1 & 2 (for fixed indices on axes 0 & 3)
# as though those 48x48 values were all a single 1D chain, and to take the max among them. The net effect
# is to replace axes 1 & 2 (again, for each fixed pair of indices on axes 0 & 3) with a scalar, namely the
# max value.  The result will be a 500x3 array holding the maxR, maxG, and maxB values for each of the 500 images.
max_RGB = images.max(axis=(1,2))  
max_RGB.shape  # No need for print() -- notebook will display the last variable referenced by default

(500, 3)

In [4]:
# Now we want to broadcast-divide all the R,G,B values on each by their respective maxes in one vectorized swoop.
# But (500,3) isn't compatible with (500,48,48,3) (make sure you understand *why* based on broadcasting rules).
# But we can make them compatible by manually inserting size-1 dimensions so that the maxes take on shape
# (500, 1, 1, 3).  And that allows us to divide in a vectorize numpythonic way.  Note: no need to have a new variable
# point to the reshaped array, since once the division is over, we don't need to hold on to the reshaped version.
normed_images = images / max_RGB.reshape(500, 1, 1, 3)

# Note: slicing max_RGB with some np.newaxis-es thrown in would also have worked (remembering, slicing and/or
# using newaxis and/or using reshape change only the *view*, not the *data*. Like this...
# normed_images = images / max_RGB[:, np.newaxis, np.newaxis, :]

In [5]:
# That's it.  Four-line solution(after importing numpy). Did it work?  Here's a sanity check...

# Are all the max-values now 1?
print(normed_images.max(axis=(1,2)))

# And more rigorously
np.all(normed_images.max(axis=(1,2)) == 1.0)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 ...
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


True

### (3,48,48)-based solution

In [6]:
import numpy as np
# Generate a collection of 500 48x48 RGB images
images = np.random.rand(500, 3, 48, 48)

In [7]:
# Find the max-intensity within each color-channel of each image...

# The `axis` option tells max() to treat all the data along axes 2 & 3 (for fixed indices on axes 0 & 1)
# as though those 48x48 values were all a single 1D chain, and to take the max among them. The net effect
# is to replace axes 2 & 3 (again, for each fixed pair of indices on axes 0 & 1) with a scalar, namely the
# max value.  The result will be a 500x3 array holding the maxR, maxG, and maxB values for each of the 500 images.
max_RGB = images.max(axis=(2,3))  
max_RGB.shape  # No need for print() -- notebook will display the last variable referenced by default

(500, 3)

In [8]:
# Now we want to broadcast-divide all the R,G,B values on each by their respective maxes in one vectorized swoop.
# But (500,3) isn't compatible with (500,3, 48,48) (make sure you understand *why* based on broadcasting rules).
# But we can make them compatible by manually inserting size-1 dimensions so that the maxes take on shape
# (500, 3, 1, 1).  And that allows us to divide in a vectorize numpythonic way.  Note: no need to have a new variable
# point to the reshaped array, since once the division is over, we don't need to hold on to the reshaped version.
normed_images = images / max_RGB.reshape(500, 3, 1, 1)

# Note: slicing max_RGB with some np.newaxis-es thrown in would also have worked (remembering, slicing and/or
# using newaxis and/or using reshape change only the *view*, not the *data*. Like this...
# normed_images = images / max_RGB[:, :, np.newaxis, np.newaxis]
# Or, since the 500 & 3 dims are grouped, we could have used an Ellipsis:
# normed_images = images / max_RGB[..., np.newaxis, np.newaxis]

In [9]:
# That's it.  Four-line solution (after importing numpy). Did it work?  Here's a sanity check...

# Are all the max-values now 1?
print(normed_images.max(axis=(2,3)))

# And more rigorously
np.all(normed_images.max(axis=(2,3)) == 1.0)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 ...
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


True

### (48,48,3,500)-based solution
Just for kicks... what if we'd decided to stick with (48,48,3) and cataloged the 500 different images along the *last* axis?  Other than having to now have `axis=(0,1)` in the argument to `np.max()`, we would get the benefit here of automatic broadcasting of the division without needing to reshape the results of `max()`.

How come? Well, the shape of `max.RGB` would now be `(3,500)`, and since we line up two arrays along their *terminal* axes to determine broadcast compatibility, this and our main `images` array would now be compatible. Thus, Numpy would *automatically* prepend two length-1 axes to `max.RGB` (that's broadcast rule 3 from the notes), clone values along the new axis0 and axis1 automatically to expand them to 48x48 (that's broadcast rule 2), and then perform elementwise division.

If it feels weird to have the 500 count along the last axis, is it worth doing things this way?  Probably not -- reshapinng or using newaxis is essentially a no-cost operation ("no-op") because it only changes the *view* of our `max.RGB` array, and using one of the two shapes in the solutions above (with 500 along axis0) probably feels more natural.  We're including this scenario here mostly for completeness's sake (and to drive home how broadcasting works).

In [1]:
import numpy as np
# Generate a collection of 500 48x48 RGB images
images = np.random.rand(48, 48, 3, 500)

In [2]:
# Find the max-intensity within each color-channel of each image...

# The `axis` option tells max() to treat all the data along axes 0 & 1 (for fixed indices on axes 2 & 3)
# as though those 48x48 values were all a single 1D chain, and to take the max among them. The net effect
# is to replace axes 0 & 1 (again, for each fixed pair of indices on axes 2 & 3) with a scalar, namely the
# max value.  The result will be a 3x500 array: 500 maxR values, then 500 maxG values, then 500 maxB values.
max_RGB = images.max(axis=(0,1))  
max_RGB.shape  # No need for print() -- notebook will display the last variable referenced by default

(3, 500)

In [5]:
# Now we want to broadcast-divide all the R,G,B values on each by their respective maxes in one vectorized swoop.
# since (3,500) is broadcast compatible with (48,48, 3, 500) (make sure you understand *why* based on broadcasting rules),
# the vectorization happens automatically, w/o any *explicit* reshaping on our part (Numpy handles it behind the scenes).
normed_images = images / max_RGB
print(normed_images.shape)

(48, 48, 3, 500)


In [6]:
# That's it.  Four-line solution (after importing numpy). Did it work?  Here's a sanity check...

# Are all the max-values now 1? NOTE: the 500x3 maxes are now laid out in 3x500 shape --
# all 500 red maxes, then all 500 green maxes, then all 500 blue maxes
print(normed_images.max(axis=(0,1)))

# And more rigorously
np.all(normed_images.max(axis=(0,1)) == 1.0)

[[1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]]


True